### PR TITLE
Make `arwheadnlp.f(x)` allocation-free

### PR DESCRIPTION
**Pull request by paraynaud**
@tmigot, following this [discussion](https://github.com/JuliaSmoothOptimizers/PartiallySeparableNLPModels.jl/discussions/63#discussioncomment-4450738).

### CODE REVIEW

**Review by tmigot — APPROVED** [review]
Thanks @paraynaud 
Good catch

**Comment by paraynaud** [comment]
@tmigot I tested `grad!` for this new `arwhead`, you will be happy to know that it doen't make allocations, contrary to the previous version!

**Comment by tmigot** [comment]
Awesome!

**Comment by tmigot** [comment]
Connected to #243

**Pull request merged**
